# Default values for headlamp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of desired pods
replicaCount: 1

global:
  # -- namespace or a project name (in case of OpenShift)
  edpName: ""
  # -- a cluster DNS wildcard name
  dnsWildCard:
  # -- platform type that can be "kubernetes" or "openshift"
  platform: "openshift"
  # -- Keycloak URL
  keycloakUrl: "https://keycloak.example.com"

image:
  # -- EDP headlamp Docker image name. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/edp-headlamp)
  repository: epamedp/edp-headlamp
  # -- If not defined then .Chart.AppVersion is used
  # -- EDP headlamp Docker image tag. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/edp-headlamp/tags)
  tag:

# -- An optional list of references to secrets in the same namespace to use for pulling any of the images used
imagePullSecrets: []
# -- Overrides the name of the chart
nameOverride: ""
# -- Overrides the full name of the chart
fullnameOverride: ""

config:
  # -- base url path at which headlamp should run
  baseURL: ""
  oidc:
    enabled: false
    # -- OIDC client ID
    clientID: ""
    # -- OIDC client secret name
    clientSecretName: ""
    # -- OIDC client secret key
    clientSecretKey: ""
    # -- OIDC issuer realm
    issuerRealm: ""
    # -- OIDC scopes to be used
    scopes: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.(If not set and create is true, a name is generated using the fullname template)
  name: ""

# -- Annotations to add to the pod
podAnnotations: {}

# -- Headlamp pods' Security Context
podSecurityContext:
  {}
  # fsGroup: 2000

# -- Headlamp containers Security Context
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Kubernetes Service type
  type: ClusterIP
  # -- Kubernetes Service port
  port: 80

ingress:
  # -- Annotations for Ingress resource
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Hostname(s) for the Ingress resource
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- CPU/Memory resource requests/limits
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Node labels for pod assignment
nodeSelector: {}

# -- Toleration labels for pod assignment
tolerations: []

# -- Affinity settings for pod assignment
affinity: {}
