apiVersion: v1.edp.epam.com/v1
kind: EDPComponent
metadata:
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
  name: edp-headlamp
spec:
  type: headlamp
  url: https://edp-headlamp-{{ .Values.global.edpName }}.{{ .Values.global.dnsWildCard }}
  visible: true
  icon: "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMjUuNTEgMzIiPjxwYXRoIGZpbGw9IiMwMDAiIGQ9Ik0yNS41MDYgMjAuMzF2LTcuNTE2bC0xLjk5LTIuNTk3VjUuODNsLTYuMzgzLTIuMjk0VjBoLTguNzZ2My41MzdMMS45OSA1LjgzMXY0LjM2NkwwIDEyLjc5NHY3LjUxN2wxLjk5IDIuNjhMMCAyOS4xODEgMTIuNzY3IDMybDEyLjczOS0yLjgxOS0xLjk5LTYuMTlaIj48L3BhdGg+PHBhdGggZmlsbD0iI2ZmZjIwMCIgZD0iTTEyLjc2NyAyMi45OTFhNi4zODMgNi4zODMgMCAxIDAgMC0xMi43NjYgNi4zODMgNi4zODMgMCAwIDAgMCAxMi43NjZ6Ij48L3BhdGg+PC9zdmc+"