{{- if eq .Values.global.platform "openshift" -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
    host: edp-headlamp-{{ .Values.global.edpName }}.{{ .Values.global.dnsWildCard }}
    tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
    to:
        kind: Service
        name: {{ .Chart.Name }}
        weight: 100
    wildcardPolicy: None
status:
    ingress: []
{{- end -}}
